version: 2
jobs:
  build:
    working_directory: ~/store
    docker:
      - image: circleci/python:2.7.13
      - image: circleci/mysql:5.7
        environment:
          MYSQL_DATABASE: circle_test
          MYSQL_USER: root
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python manage.py test tests
      - store_artifacts:
          path: test-reports/
          destination: tr1