version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.3
    working_directory: ~/circleci-docs

machine:

    python:
        version: 2.7.6

dependencies:
    pre:
        - pip install -U pip

test:
    override:
        - ./test.sh

notify:
  webhooks:
    # A list of hashes representing hooks. Only the url field is supported.
    - url: https://hook.lesschat.com/circleci/6254d4312f2440e1a1767475b266d8eb