version: 2
jobs:
  build:
    working_directory: ~/store
    docker:
      - image: circleci/python:2.7.13
      - image: circleci/mysql:5.7
        environment:
          MYSQL_DATABASE: circle_test
          MYSQL_USER: root
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_HOST: "%"
          MYSQL_ROOT_PASSWORD: '123456'
    steps:
      - checkout
      - run:
          command: |
            sudo pip install -r requirements.txt
      - run:
          command: |
            python manage.py test tests
      - store_artifacts:
          path: test-reports/
          destination: tr1